language: go
go_import_path: github.com/ethereum/go-ethereum
sudo: false
jobs:
  include:
    # This builder only tests code linters on latest version of Go
    - stage: lint
      os: linux
      dist: xenial
      go: 1.12.x
      env:
        - lint
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go run build/ci.go lint
    - stage: build
      os: linux
      dist: xenial
      go: 1.11.x
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES
    - stage: build
      os: linux
      dist: xenial
      go: 1.12.x
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES
    - stage: build
      os: linux
      dist: xenial
      go: 1.13.x
      script:
        - go run build/ci.go install
        - go run build/ci.go test -coverage $TEST_PACKAGES
    - stage: Develop Release
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io/amis
      - make docker
      - make docker.push
      if: branch =~ ^indexer-([0-9]+.)+[0-9]+ AND (NOT type IN (pull_request))
    - stage: Staging Release
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin quay.io/amis
      - make docker
      - make docker.push
      if: tag =~ ^indexer-([0-9]+.)+[0-9]+
      env: DOCKER_IMAGE_TAG="$TRAVIS_TAG"
